name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: action-pack/gitlab-sync@v3
      with:
        url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.GITLAB_USERNAME }}
        token: ${{ secrets.GITLAB_TOKEN }}
